pipeline:
  name: PipelineNested123
  identifier: PipelineNested123
  projectIdentifier: DoNotDelete_Brooke2
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: CDStageRemote
          versionLabel: v1
          gitBranch: main-patch
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
