pipeline:
  name: remotePipeline
  identifier: remotePipeline
  tags: {}
  projectIdentifier: DoNotDelete_Brooke
  orgIdentifier: default
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: remoteService
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  variables:
                    - name: var1
                      type: String
                      required: true
                      value: <+input>
                    - name: var2
                      type: String
                      description: test
                      required: true
                      value: <+input>
                    - name: var3
                      type: String
                      description: gbhdbhy
                      value: <+input>
                    - name: var4
                      type: String
                      value: <+input>
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: env1
                environmentInputs:
                  identifier: env1
                  type: PreProduction
                  variables:
                    - name: var1
                      type: String
                      value: <+input>
                      description: "Description for Environment "
                      required: true
                    - name: var2
                      type: String
                      value: <+input>
                      required: true
                    - name: var3
                      type: String
                      value: <+input>
                      description: optional
                    - name: var4
                      type: String
                      value: <+input>
                deployToAll: true
                infrastructureDefinitions: <+input>
              - environmentRef: env2
                environmentInputs:
                  identifier: env2
                  type: PreProduction
                  variables:
                    - name: var1
                      type: String
                      value: <+input>
                      description: "Description for Environment "
                      required: true
                    - name: var2
                      type: String
                      value: <+input>
                      required: true
                    - name: var3
                      type: String
                      value: <+input>
                      description: optional
                    - name: var4
                      type: String
                      value: <+input>
                deployToAll: true
                infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 'hi'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
